# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  rideshareapi:
    container_name: "rideshareapi"
    build:
      context: .
      dockerfile: src/RideShare.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5136:5136
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
